### PR TITLE
Update image for datadog agent

### PR DESCRIPTION
**Pull request by minedetector**
INF-2547

### CODE REVIEW

**Comment by take-five** [comment]
Is there release notes for this release?

**Comment by minedetector** [comment]
Not currently put I felt more comfortable testing it in kubernetes since I have done it once already

**Comment by take-five** [comment]
I'd rather we were able to check the changelog before deploying it anywhere (that's where any upgrade should start - by checking release notes).

**Comment by minedetector** [comment]
Since no changelogs or release notes are present at this time the update will be canceled

**Pull request closed without merging**
